### ISSUE TITLE
Lijst blijft leeg

### ISSUE THREAD

**Issue by DieterKoblenz** [svdgraaf/appie#1]
Allereerst, fantastisch project! Ik zie hier een nuttige koppeling met mijn huidige systeem maar krijg het niet werkend. 

In python doe ik volgens de readme de drie stappen maar list eindigt altijd met "None". Als ik inlog op mijn appie op of via chrome dan zie ik met add (ondanks True) geen nieuwe producten verschijnen.

**Comment by ricohageman** [comment]
Dit komt omdat de methode '_update_list' nog niet is aangeroepen en dus is de list nog steeds leeg.

**Comment by DieterKoblenz** [comment]
Hoe kan ik die aanroepen dan?

**Comment by ricohageman** [comment]
Een extra regel met: 'cliënt._update_list()' voordat je 'print client.list' hebt

**Comment by DieterKoblenz** [comment]
Dat heb ik geprobeerd, vervolgens krijg ik dat de "payload" niet gedefinieerd is.

**Comment by ricohageman** [comment]
Dat klopt idd, heb hiervoor een pull request aangemaakt. Maar anders kan je ook hier mijn laatste versie pakken. https://github.com/RicoHageman/appie

**Comment by DieterKoblenz** [comment]
Ga ik die proberen! Dank!

**Comment by DieterKoblenz** [comment]
Laatste versie (https://github.com/RicoHageman/appie) werkt perfect inclusief delete!
